name: Workflow Test

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'workflow/leviosam2.py'
      - 'workflow/workflow-test.py'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**'
      - 'workflow/leviosam2.py'
      - 'workflow/workflow-test.py'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run workflow-test
        run: |
            cd workflow
            python workflow-test.py
